export enum IconType {
  arrowDownCircle = 'arrow-down-circle',
  arrowUturnLeft = 'arrow-uturn-left',
  checkCircle = 'check-circle',
  chevronRight = 'chevron-right',
  envelope = 'envelope',
  eye = 'eye',
  globeAlt = 'globe-alt',
  heart = 'heart',
  minus = 'minus',
  minusCircle = 'minus-circle',
  pencil = 'pencil',
  rocketLaunch = 'rocket-launch',
  share = 'share',
  shoppingBag = 'shopping-bag',
  trash = 'trash',
  userCircle = 'user-cicrle',
  userGroup = 'user-group',
  xMark = 'x-mark',
}
