export enum IconType {
  arrowDownCircle = 'arrow-down-circle',
  arrowUturnLeft = 'arrow-uturn-left',
  chevronRight = 'chevron-right',
  envelope = 'envelope',
  eye = 'eye',
  globeAlt = 'globe-alt',
  heart = 'heart',
  rocketLaunch = 'rocket-launch',
  share = 'share',
  shoppingBag = 'shopping-bag',
  userCircle = 'user-cicrle',
  userGroup = 'user-group',
  xMark = 'x-mark',
}
